apiVersion: apps/v1
kind: Deployment
metadata:
  name: instrumented-logs
spec:
  selector:
    matchLabels:
      app: instrumented-logs
  template:
    metadata:
      labels:
        app: instrumented-logs
    spec:
      containers:
      - name: instrumented-logs
        image: yaalexf/instrumented-logs
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8080
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_ANALYTICS_ENABLED
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: instrumented-logs
spec:
  ports:
  - name: https
    port: 8080
    targetPort: 8080
  selector:
    app: instrumented-logs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: instrumented-logs
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /instrumented-logs
        backend:
          serviceName: instrumented-logs
          servicePort: 8080